---
-
  name: Update Favo Edge binary
  hosts:
    - all
  become: yes
  tasks:
    ## update & upgrade system
    - name: Update & upgrade system
      apt:
        upgrade: yes
        update_cache: yes

    ## stop favo-chain service
    - name: Stop favo edge service
      systemd:
        state: stopped
        name: favo-chain

    ## get the latest release
    - name: Get latest release link
      uri:
        url: https://api.github.com/repos/0xFavo/favo-chain/releases/latest
        return_content: true
      register: edge_release

    ## download the latest release
    - name: Download latest Favo Edge release
      get_url:
        url: "{{ edge_release.json.assets[3].browser_download_url }}"
        dest: /tmp/favo-chain.tar.gz
        force: yes

    ## create temp dir for release
    - name: Create temp dir for Favo Edge release
      file:
        path: /tmp/favo-chain
        state: directory

    ## unpack release tar
    - name: Unpack Favo Edge release
      unarchive:
        remote_src: yes
        src: /tmp/favo-chain.tar.gz
        dest: /tmp/favo-chain

    ## set favo-chain to PATH
    - name: Place Favo Edge binary to PATH
      copy:
        remote_src: yes
        src: /tmp/favo-chain/favo-chain
        dest: /usr/local/bin/
        mode: a+x
        force: yes

    ## remove release temp dir
    - name: Remove temp Favo Edge release dir
      file:
        state: absent
        path: /tmp/favo-chain

    ## start favo edge service
    - name: Start favo-chain service
      systemd:
        state: restarted
        name: favo-chain
        daemon_reload: yes
        enabled: yes